### PR TITLE
feat: AWS Managed Prometheus sigv4 integration

### PR DESCRIPTION
**Pull request by a7i**
closes https://github.com/opencost/opencost/issues/1906

```bash
helm template opencost . --set opencost.prometheus.amp.enabled=true --set opencost.prometheus.internal.enabled=false --set opencost.prometheus.amp.workspaceId=my-workspace-id
```

result:
```yaml
---
# Source: opencost/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencost
  labels:
    helm.sh/chart: opencost-1.19.3
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.105.2"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: opencost/templates/clusterrole.yaml
# Cluster role giving opencost to get, list, watch required resources
# No write permissions are required
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opencost
  labels:
    helm.sh/chart: opencost-1.19.3
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.105.2"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - deployments
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
# Source: opencost/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opencost
  labels:
    helm.sh/chart: opencost-1.19.3
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.105.2"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencost
subjects:
  - kind: ServiceAccount
    name: opencost
    namespace: default
---
# Source: opencost/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opencost
  labels:
    helm.sh/chart: opencost-1.19.3
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.105.2"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
  type: ClusterIP
  ports:
    - name: http
      port: 9003
      targetPort: 9003
    - name: http-ui
      port: 9090
      targetPort: 9090
---
# Source: opencost/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  labels:
    helm.sh/chart: opencost-1.19.3
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.105.2"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencost
      app.kubernetes.io/instance: opencost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencost
        app.kubernetes.io/instance: opencost
    spec:
      serviceAccountName: opencost
      containers:
        - name: opencost
          image: "quay.io/kubecost1/kubecost-cost-model:prod-1.105.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
              name: http
          resources:
            limits:
              cpu: 999m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 55Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://localhost:8005/workspaces/my-workspace-id"
            - name: CLUSTER_ID
              value: "default-cluster"
            # If username, password or bearer_token are defined, pull from secrets
        - name: opencost-ui
          image:  "quay.io/kubecost1/opencost-ui:prod-1.105.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http-ui
          resources:
            limits:
              cpu: 999m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 55Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
        - name: sigv4proxy
          image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
          - --name
          - aps
          - --region
          - us-west-2
          - --host
          - aps-workspaces.us-west-2.amazonaws.com
          - --port
          - :8005
          ports:
          - name: aws-sigv4-proxy
            containerPort: 8005
```

In particular take note of:
```
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://localhost:8005/workspaces/my-workspace-id"
```

And the sidecar container `sigv4proxy`

### CODE REVIEW

**Comment by mattray** [comment]
@a7i thanks a lot for contributing this!

**Comment by a7i** [comment]
Do I need to bump the chart or is that done automatically?

**Comment by mattray** [comment]
Merged in https://github.com/opencost/opencost-helm-chart/commit/d231abb78c4e6155f60e2b0d456600bca287deae

Thanks @a7i!

**Comment by HiphopopotamusRhymenoceros** [comment]
@a7i Does this remove the need to have a prometheus server running within the cluster? Just deploying this helm chart setting _opencost.prometheus.amp.enabled=true, opencost.prometheus.internal.enabled=false, and opencost.prometheus.amp.workspaceId=my-workspace-id_ isn't working. I've verified access from all containers to amp as well. Is there another step that I'm missing?

**Comment by a7i** [comment]
I have this running in AWS, below is my config:

```
opencost:
  prometheus:
    external:
      enabled: false
    internal:
      enabled: false
    amp:
      enabled: true
      workspaceId: $(WORKSPACE_ID)
      
  sigV4Proxy:
    region: $(AWS_REGION)
    host: aps-workspaces.$(AWS_REGION).amazonaws.com
    port: 8080
```

replace the values in $(..) to match your config

**Pull request closed without merging**
