### PR TITLE
FIXES #10 - Publish Chart to a proper helm repository

### LINKED ISSUE #10: Publish the helm chart to a registry
It would be much easier to install and track if the chart is published to a registry with a tag

### PR DESCRIPTION
**Pull request by toscott**
What this is and why do we need it
Enabling the publish workflow for helm to allow direct helm installs from github

Extras
Refactoring to (seemingly) standard convention for chart releaser to allow for easy addition if there are more opencost charts down the line

Let me know if we would rather keep the current project structure, I can swap it back around. 

This does require a "gh-pages" branch be created in the primary project for the chart-releaser to register the helm chart in the index.yaml file.

### CODE REVIEW

**Comment by toscott** [comment]
Rebased to fix conflict with Chart.yaml

**Comment by toscott** [comment]
@mattray - Let me know if you are game with this approach or want to see something different. I'm very interested in seeing it through :)

I'm currently installing the helm chart directly through my github fork.

helm repo add opencost-toscott https://toscott.github.io/opencost-helm-chart
helm search repo opencost
helm install opencost opencost-toscott/opencost

**Comment by mattray** [comment]
I'll defer to @Pokom or @AjayTripathy for their opinions given they're more experienced with more deployments.

**Comment by Pokom** [comment]
I don't have a strong opinion, I've largely been a consumer of helm charts or published to internal repositories. Unless there's a strong reason to use something else, I don't see an issue with using GitHub for hosting our charts.

**Comment by toscott** [comment]
@Pokom @AjayTripathy - Please let me know if/when you want to proceed with this and I will rebase again.

**Comment by illrill** [comment]
LGTM

**Comment by toscott** [comment]
Rebased again :)

**Comment by toscott** [comment]
I did just notice AjayTripathy commented approval on the original issue here:
https://github.com/opencost/opencost-helm-chart/issues/10#issuecomment-1416838173

**Comment by AjayTripathy** [comment]
Hosting on GH seems fine to me!

**Review by Pokom — APPROVED** [review]
:+1: Thanks for the contribution @toscott!!

**Comment by toscott** [comment]
@AjayTripathy - We will need to make a gh-pages branch in this repository for the github actions to write back to as the helm index.

It doesn't matter what is in the branch. Example here:
https://github.com/toscott/opencost-helm-chart/tree/gh-pages

**Comment by Pokom** [comment]
@toscott I can help with that :smile: Mind creating a new issue and document what's needed? I can pick this up tomorrow

**Comment by toscott** [comment]
> @toscott I can help with that 😄 Mind creating a new issue and document what's needed? I can pick this up tomorrow
Thanks Pokom. Put all the details in this issue:
https://github.com/opencost/opencost-helm-chart/issues/19

**Pull request merged**
