### PR TITLE
Fix typo in image.tag default values

### LINKED ISSUE #233: Typo in image.tag in chart version 1.42.1
The `@` symbol is missing before `sha256` in `opencost.image.tag` and `opencost.ui.image.tag` in chart version `1.42.1`. The sha256 hashes of the images are also incorrect.

### PR DESCRIPTION
**Pull request by verdel**
- Return `@` before `sha256` in `opencost.image.tag` and `opencost.ui.image.tag`
- Fix `sha256` hashes

This fixes #233

### CODE REVIEW

**Review by mkilchhofer — APPROVED** [review]
LGTM

I encountered the same issue with the chart update 1.42.0 -> 1.42.1

**Comment by rkashasl** [comment]
When the new version would be released? Renovate autoupdated opencost as it was a patch version update and now it doesn't work everywhere

**Review by toscott — APPROVED** [review]
@verdel  - Thank you for correcting this!

**Review by asdfgugus — APPROVED** [review]
LGTM 🚀

**Pull request merged**
