### PR TITLE
update image repo

### PR DESCRIPTION
**Pull request by cliffcolvin**
This pr attempts to update the container repository to ghcr and renames the containers.

old >> new
quay.io/kubecost1/kubecost-cost-model >> ghcr.io/opencost/opencost
quay.io/kubecost1/opencost-ui >> ghcr.io/opencost/opencost-ui

Another specific change is the move from prod-vX.Y.Z to X.Y.Z

### CODE REVIEW

**Review by brito-rafa — APPROVED** [review]
LGTM, the [opencost repo](https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml) needs to be updated too.

**Comment by mattray** [comment]
> LGTM, the [opencost repo](https://github.com/opencost/opencost/blob/develop/kubernetes/opencost.yaml) needs to be updated too.

https://github.com/opencost/opencost/pull/2564

**Comment by mattray** [comment]
I've rolled this up in https://github.com/opencost/opencost-helm-chart/pull/179

**Comment by toscott** [comment]
This one was merged as part of: https://github.com/opencost/opencost-helm-chart/pull/179

**Pull request closed without merging**
