### PR TITLE
feature: add nodeSelector, affinity and topologySpreadConstraint to Helm Chart

### LINKED ISSUE #16: Helm Chart Affinity, NodeSelector and TopologySpreadConstraints
To configure how the OpenCost pods are placed on nodes, we need to add the following common configs to the Helm Chart:

- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
- [Node Selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector)
- [Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/)

### PR DESCRIPTION
**Pull request by hajowieland**
Fixes #16

Added the following config in Deployment template and to Chart default values.yaml:

- affinity
- nodeSelector
- topologySpreadConstraint

And updated the version in the Chart.yaml and in the raw manifest files.

### CODE REVIEW

**Comment by illrill** [comment]
LGTM 👍

**Comment by thomasvn** [comment]
This looks good to me! Tested by running `helm template . -f values-test.yaml` with this [values-test.yaml](https://github.com/opencost/opencost-helm-chart/files/10799199/values-test.txt).

@mattray Is the version bump on the `Chart.yaml` correct here? Is each PR resulting in a version bump? Or are you batching multiple changes into a version bump?

**Comment by mattray** [comment]
@thomasvn I think we should bump with each change, in case one's breaking.

**Review by thomasvn — APPROVED** [review]
Looks great! May need to fix existing conflicts with `main` branch before merging. And I think the version bump should be to `1.0.2`. Correct @mattray?

**Comment by toscott** [comment]
1.0.3 now I think. Matt did a manual bump to get the publish workflow to run without having to delete existing releases/tags it looks like.

**Comment by mattray** [comment]
Rebased and merged: https://github.com/opencost/opencost-helm-chart/commit/c5e6f86aef0637b151179eef38962c4e595517f2

**Pull request closed without merging**
