### PR TITLE
Reformat chart templates

### PR DESCRIPTION
**Pull request by dnskr**
The PR reformats chart templates to one style with more readable blocks and indents to improve code readability.
Fixed duplicated `volumeMounts` in main container.

Similar changes: https://github.com/apache/airflow/pull/29917 https://github.com/apache/airflow/pull/29941 https://github.com/apache/airflow/pull/30312 https://github.com/minio/minio/pull/16947 https://github.com/apache/superset/pull/23681

### CODE REVIEW

**Comment by mattray** [comment]
What formatting tool did you use to reformat everything? There's a lot in there to review and I'd like to see how it was created.

**Comment by dnskr** [comment]
> What formatting tool did you use to reformat everything? There's a lot in there to review and I'd like to see how it was created.

There is no tool for that as I know. It was created manually.

**Comment by eric-engberg** [comment]
Just ran into the duplicate volumeMounts.  Had to fix it locally to get anything working

**Review by toscott — APPROVED** [review]
lgtm.
Thanks for another round of changes @dnskr!

**Pull request merged**
