### PR TITLE
Fixes #13 Additional labels in servicemonitor.yaml template

### LINKED ISSUE #13: Additional labels are not assigned to a services monitor based on values.yaml config
Hey, 
Noticed that `additionalLabels`  has no effect to servicemonitor.yaml template labels
```yaml
  metrics:
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      ## The label to use to retrieve the job name from.
      ## jobLabel: "app.kubernetes.io/name"
      namespace: ''
      namespaceSelector: {}
      ## Default: scrape .Release.Namespace only
      ## To scrape all, use the following:
      ## namespaceSelector:
      ##   any: true
      scrapeInterval: 30s
      # honorLabels: true
      targetLabels: []
      relabelings: []
      metricRelabelings: []
```

Curently service monitor template contains the following regarding labels:
```yaml
...
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
```

Need to add something like this:

```yaml
...
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
    {{- if .Values.opencost.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.opencost.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
```

### PR DESCRIPTION
**Pull request by andriktr**
Fixes #13  `servicemonitor.yaml` template to include additional labels based on `values.yaml`

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Hey @andriktr this lgtm but can you help me understand how this was tested?

**Comment by andriktr** [comment]
Hi,
A bit confused with your question as it quite obvious. 
I have tested it in my dev environment. 
Currently servicmonitor.yaml includes only label from {{- include "opencost.labels" . | nindent 4 }}. 
And labels specified in`values.yaml` under `opencost.metrics.serviceMonitor.additionalLabels`are not included.
So adding 
```
    {{- if .Values.opencost.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.opencost.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
```
into servicemonitor.yaml fixes the problem and `opencost.metrics.serviceMonitor.additionalLabels` are also included as expected.

**Comment by illrill** [comment]
LGTM

**Comment by mattray** [comment]
Merged

**Pull request closed without merging**
