### PR TITLE
Configurable ports

### PR DESCRIPTION
**Pull request by mattray**
This sets environment variables and uses the values of API_PORT and UI_PORT within the `deployment.yaml` to ensure the ports are synced up. API_SERVER is also set for within the opencost-ui's `default.nginx.conf`

Tested with vanilla 1.107.1 containers as well as with builds using the exposed ports.

### CODE REVIEW

**Review by brito-rafa — APPROVED** [review]
FWIW, I tested this change. LGTM.

```
% helm template opencost ./charts/opencost > ~/tmp/opencost.yaml 

% helm template opencost ./charts/opencost --set opencost.exporter.apiPort=19003 --set opencost.ui.uiPort=19090 > ~/tmp/opencost-customports.yaml

% diff --suppress-common-lines -y ~/tmp/opencost.yaml ~/tmp/opencost-customports.yaml
            - containerPort: 9003			      |	            - containerPort: 19003
              port: 9003				      |	              port: 19003
              port: 9003				      |	              port: 19003
              value: "9003"				      |	              value: "19003"
            - containerPort: 9090			      |	            - containerPort: 19090
              value: "9003"				      |	              value: "19003"
              value: "9090"				      |	              value: "19090"
              port: 9090				      |	              port: 19090
              port: 9090				      |	              port: 19090
```

**Review by brito-rafa — APPROVED** [review]
LGTM

```
% helm template opencost ./charts/opencost > ~/tmp/opencost-defaults.yaml
% helm template opencost ./charts/opencost --set opencost.exporter.apiPort=19003 --set opencost.ui.uiPort=19090 > ~/tmp/opencost-customports.yaml
% diff --suppress-common-lines -y ~/tmp/opencost-defaults.yaml ~/tmp/opencost-customports.yaml
            - containerPort: 9003			      |	            - containerPort: 19003
              port: 9003				      |	              port: 19003
              port: 9003				      |	              port: 19003
              value: "9003"				      |	              value: "19003"
            - containerPort: 9090			      |	            - containerPort: 19090
              value: "9003"				      |	              value: "19003"
              value: "9090"				      |	              value: "19090"
              port: 9090				      |	              port: 19090
              port: 9090				      |	              port: 19090
```

**Review by brito-rafa — CHANGES_REQUESTED** [review]
Actually, the `charts/opencost/templates/service.yaml` needs to be changed as well.

**Comment by brito-rafa** [comment]
FWIW, I put a PR on your branch: https://github.com/mattray/opencost-helm-chart/pull/1

**Comment by mattray** [comment]
Thanks! I'll merge this with a version bump once 1.108 is released

**Review by brito-rafa — APPROVED** [review]
LGTM

**Pull request merged**
